version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flick-console
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:9000"  # Only bind to localhost, not public internet
    env_file:
      - .env
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    networks:
      - flick-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  flick-network:
    driver: bridge

